{
    "0": "Beckon Sign \"Urge to Do Business -Kitty-Cat Eyes-\"",
    "1": "Beckon Sign \"Overwhelming Urge to Do Business -Kitty-Cat Eyes-\"",
    "2": "Beckon Sign \"Doing Business with the Goutoku-ji Gods.\"",
    "3": "Beckon Sign \"Striking a Deal with the Goutoku-ji Gods.\"",
	
    "4": "Leaf Skill \"Camouflage Shrub\"",
    "5": "Leaf Skill \"Shrouded Camouflage Shrub\"",
    "6": "Leaf Skill \"Invisible to All in the Forest\"",
    "7": "Leaf Skill \"Being One with the Forest\"",
	
    "8": "Mountain Sign \"Cloudy Nagasakiissai Raceme\"",
    "9": "Mountain Sign \"Foggy Nagasakiissai Raceme\"",
    "10": "Mountain Apparition \"Smoky Nagasakiissai Raceme\"",
    "11": "Mountain Apparition \"Stormy Nagasakiissai Raceme\"",
	
    "12": "Sellers of Discord \"Unconnected Marketeers\"",
	
    "16": "Blade Exhaustion Sign \"Mountain Murder\"",
    "18": "Blade Exhaustion Sign \"Bloody Mountain Murder\"",
    "20": "Spring Sign \"Surprise Spring\"",
    "22": "Dog Sign \"Stray Dog's Walk\"",
    "24": "Hound Sign \"Mountain Hound's Walk\"",
    "26": "Spinning Top \"Koma-Inu Spin\"",
    "29": "Spinning Top \"Curl Up and Die\"",
    "30": "Koma Sign \"Solitary A-Um Breathing\"",
    "34": "Magic Sign \"Instant Bodhi\"",
    "36": "Magic Sign \"Bodhi in an Instant\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "40": "Magic Sign \"Gigantic Pet Bullet Lifeform\"",
    "42": "Jizo \"Criminal Salvation\"",
    "44": "Jizo \"Hellfire Salvation\"",
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myōga Ginger \"Forget Your Name\"",
    "54": "Broadleaf Sign \"Tanabata Star Festival\"",
    "58": "Myōga Blessing \"Behind You\"",
    "62": "Dance Sign \"Behind Festival\"",
    "66": "Mad Dance \"Tengu-odoshi\"",
    "68": "Mad Dance \"Frenzied Tengu-Frightening\"",
    "70": "Back Sign \"Halo of the Secret God\"",
    "73": "Back Sign \"Halo of the Absolute Secret God\"",
    "74": "Hidden Summer \"Scorch By Hot Summer\"",
    "76": "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
    "78": "Hidden Fall \"Die of Famine\"",
    "80": "Hidden Fall \"Preta of Abnormal Blight\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Hidden Spring \"April Wizard\"",
    "88": "Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
    "90": "\"Hidden Breezy Cherry Blossom\"",
    "94": "\"Hidden Perfect Summer Ice\"",
    "98": "\"Hidden Crazy Fall Wind\"",
    "102": "\"Hidden Extreme Winter\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Secret Ceremony \"Reverse Invoker\"",
    "110": "Secret Ceremony \"Rear Shots of Betrayal\"",
    "111": "Secret Ceremony \"Danmaku Dupion\"",
    "112": "Secret Ceremony \"Fire of Ena\"",
    "113": "Secret Ceremony \"Kyōgen of the Back Door\"",
    "114": "Secret Ceremony \"Matarah Dukkha\"",
    "115": "Secret Ceremony \"Sword of the Seven Stars\"",
    "116": "Secret Ceremony \"Performers Unattached to Society\"",
    "117": "\"The Back Face's Dark Sarugaku\"",
    "118": "\"Anarchy Bullet Hell\""
}