{
    "0": "Prison \"Stone Maze\"",
    "2": "Purgatory \"Stone Labrynth\"",
    "4": "Memory \"Stillborn in Limbo\"",
    "6": "Truama \"Forever Stuck in Limbo\"",
	
    "8": "Consequnce For Kindness \"Heavy Stone Baby\"",
    "10": "Death By Kindness \"Two-Ton Stone Baby\"",
    "12": "\"Drowning in the Sanzu River\"",
    "14": "\"The Sanzu River's Pouring Watery Grave\"",
    "16": "Hungry Ushi-Oni \"Bovinal Demon Siege -Piranha-\"",
    "17": "Hungry Ushi-Oni \"Bovinal Demon Siege -Shark-\"",
    "18": "Ravenous Ushi-Oni \"Bovinal Demon Siege -Jaws-\"",
    "19": "Ravenous Ushi-Oni \"Bovinal Demon Siege -Megalodon-\"",
	
    "20": "Ember \"Purgatordeal of Water Distribution\"",
    "21": "Ablaze \"Elite-Level Purgatordeal of Water Distribution\"",
    "22": "Inferno \"Hell-Level Purgatordeal of Water Distribution\"",
    "23": "Entrence to Hell \"Ultimate Purgatordeal of Water Distribution\"",
    "24": "Dim Light \"Purgatordeal of Surveying\"",
    "25": "Bright Light \"Elite-Level Purgatordeal of Surveying\"",
    "26": "Heavenly Light \"Hell-Level Purgatordeal of Surveying\"",
    "27": "Entrence to Heaven \"Ultimate Purgatordeal of Surveying\"",
    "28": "Reflection \"Purgatordeal of Oniwatari\"",
    "29": "Judgement \"Elite-Level Purgatordeal of Oniwatari\"",
    "30": "Final Judgement \"Hell-Level Purgatordeal of Oniwatari\"",
    "31": "Heaven and Hell \"Ultimate Purgatordeal of Oniwatari\"",
	
    "32": "\"Tortoiseshell Hell\"",
    "36": "Grim Path \"Beast Yakuza\"",
    "37": "Grim Path \"Mangy Beast Yakuza\"",
    "38": "The Extreme Path \"Devilish Beast Yakuza\"",
    "39": "The Extreme Path \"Otter Oyabun\"",
    "40": "Dragon Legend \"Scales of the Jidiao\"",
	
    "44": "Break-Proof Haniwa \"Archer Formation -Robin Hood-\"",
    "46": "Undying Haniwa \"Bowmaster Formation -Nasu no Yoichi-\"",
    "48": "Haniwa Shield \"Protect the General!\"",
    "50": "Haniwa Bulwark \"We Sacrifice Ourselves For Our General!\"",
    "52": "Cavalry Formation \"Dark Horse Haniwa\"",
    "54": "White Cavalry Formation \"Haniwa Knights in Shining Armor\"",
    "56": "Last Resort \"Haniwa Seize -Winning the Battle-\"",
    "58": "Last Resort \"Haniwa Crusade -Winning the War-\"",
	
    "60": "Stable Sculpting Art \"Magical Squares\"",
    "62": "Planetary Sealing Art \"Mystical Squares\"",
    "64": "Perfect Circle \"One's Overlapping Desires\"",
    "66": "Flawless Circle \"Aphrodite's Wilting Flower\"",
    "68": "Linear Illusion \"A Journey Back To Square One\"",
    "70": "Playing God \"The Two-Sided World of Makai\"",
    "72": "Created Idol \"Haniwa Companion\"",
    "73": "Created Idol \"Haniwa Lance Corporal\"",
    "74": "Cherished Idol \"Head Haniwa General\"",
    "75": "Cherished Idol \"True Haniwa Hero\"",
    "76": "Idola Deus \"Deity Sculpting Art\"",
    "80": "Q.E.D. \"Geometric Monster\"",
    "83": "Q.E.D. \"The Tyrannic Monster of the Magic Four\"",
    "84": "Creation of Haniyasu \"Innocent Artist -Crafting Rejected Masterpieces-\"",

    "88": "Bloodshed \"Chicken Admist War\"",
    "89": "Hellish Light \"Closing the Gate to Hell -Doom Light House-\"",
    "90": "Sea of Divine Spirits \"All-Spirit Oniwatari\"",
    "91": "Quick Draw \"Fastest in the West -Thrilling Shot-\"",
    "92": "Dashing Through the Snow \"Lightning Neigh\"",
    "93": "Cattle Roundup \"Dense Crowd -Muster-\"",
    "94": "Uncontrollable Berserk \"Beast Epidemicity\"",
    "95": "Primal Hunger \"Triangle Chase -Wolf Instinct-\"",
    "96": "Space Sherrif Shooting \"Black Pegasus Meteor Shot\"",
    "97": "Brimming Beastly Power \"Muscle Explosion\"",
    "98": "\"Follow Me, Fearless!\"",
    "99": "\"Demon Hoi Polloi Titan -Helpless Prey-\"",
    "100": "\"Devilish Deeds of the Wily Beast -Karmic Wind-\"",

    "159": "Mangy Excellence \"To Overwhelm an Enemy\"", 
    "161": "Devilish Excellence \"Absolute Submission\"", 
    "163": "Metropolis Guardian \"Guarding the Mozu Tombs\"",
    "167": "Haniwa Entombing \"8000 Idols in Isolation\""
}