{
    "0": "Ice Sign \"Ultimate Blizzard\"",
    "2": "Water Sign \"Tail Fin Slap\"",
    "6": "Scale Sign \"Scale Wave\"",
    "8": "Scale Sign \"Raging Waves of the Reversed Scale\"",
    "9": "Scale Sign \"Great Raging Waves of the Reversed Scale\"",
	
    "10": "Flight Sign \"Flying Head\"",
    "14": "Neck Sign \"Close-Eye Shot\"",
    "16": "Neck Sign \"Rokurokubi Flight\"",
    "18": "Flying Head \"Multiplicative Head\"",
    "20": "Flying Head \"Seventh Head\"",
    "21": "Flying Head \"Ninth Head\"",
    "22": "Flying Head \"Dullahan Night\"",
	
    "26": "Fang Sign \"Moonlit Canine Teeth\"",
    "28": "Transformation \"Triangle Fang\"",
    "30": "Transformation \"Star Fang\"",
    "32": "Roar \"Strange Roar\"",
    "34": "Roar \"Full Moon Howling\"",
    "36": "Wolf Sign \"Star Ring Pounce\"",
    "38": "Sirius \"High-Speed Pounce\"",
    "40": "Heikyoku \"Sounds of Jetavana's Bell\"",
    "44": "Vengeful Spirit \"Hoichi the Earless\"",
    "46": "Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
    "48": "Music Sign \"Wicked Musical Score\"",
    "50": "Music Sign \"Malicious Musical Score\"",
    "51": "Music Sign \"Double Score\"",
    "52": "Koto Sign \"Sounds of Anicca's Koto\"",
    "56": "Echo Sign \"Heian's Reverberation\"",
    "58": "Echo Sign \"Echo Chamber\"",
    "60": "Koto Music \"Social Upheaval Koto Music Complement\"",
    "62": "Koto Music \"Social Upheaval Requiem\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Reverse Sign \"Danmaku Through the Looking-Glass\"",
    "70": "Reverse Sign \"Evil in the Mirror\"",
    "72": "Reverse Sign \"This Side Down\"",
    "74": "Reverse Sign \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
	
    "84": "Neck Sign \"Spine Spreading Spook\"",
    "86": "Bloody Neck Sign \"Spine Splitting Horror\"",
    "88": "Nukekubi Sign \"Searching Dullahan Heads\"",
    "90": "Nukekubi Sign \"Scavaging Dullahan Ravagers\"",
    "92": "Head Cannon \"Countless Laughing Heads\"",
    "96": "\"A Rokurokubi Among Humans\"",
    "100": "Chunnibyou Army \"Sekinvaders\"",
    "102": "Chunnibyou Army \"Sekinvaders\"",
    "104": "\"Head and Eye Apparition of Nightmares\"",
    "106": "\"Head and Eye Apparition Who Kills All it Sees\"",
	
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Drum \"Raging Temple Taiko\"",
    "111": "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Drum \"Three Strikes at Midnight\"",
    "113": "Death Drum \"Land Percuss\"",
    "114": "Fifth Drum \"Den-Den Daiko\"",
    "115": "Sixth Drum \"Alternate Sticking\"",
    "116": "Seventh Drum \"High Speed Taiko Rocket\"",
    "117": "Eighth Drum \"Thunder God's Anger\"",
    "118": "\"Blue Lady Show\"",
    "119": "\"Pristine Beat\""
}