{
    "0": "\"Tomboyish Ice Shard Flower\"",
    "1": "Frozen Wind \"Icicle Cyclone\"",
    "2": "Class in Perfection \"Lamentful Idiocy\"",
    "3": "Unreal Roundabout \"Impossible Tail Spin\"",
    "4": "\"One Fish, Two Fish, Red Fish, Blue Fish\"",
    "5": "Tragedy \"Washing Up By the Bay\"",
    "6": "Deadly Ripple \"Waves Crashing Throughout the Sea\"",
    "7": "Stormy Sea \"Roar of Sky's Rebellion\"",
    "8": "Desperation \"Flopping Like a Fish\"",
    "9": "Just Keep Swimming \"School of Fish\"",
    "10": "\"Scale Shark Lurking the Deadly Waters\"",
    "11": "Forever Asleep With the Mermaid \"Siren's Lullaby\"",
    "12": "\"Misty Ocean Revolution\"",
    "13": "Arcanum of Adam's Ale \"Fantastic Vortex\"",
}