{
    "0": "Beckon Sign \"Offering for a False Map to a Pot of Gold\"",
    "4": "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\"",
	
	"97": "Optics \"Terrestrial Camouflage\"",
	
    "8": "Forest Sign \"Unnatural Vine-Programming Tech\"",
    "10": "Forest Sign \"Artificial Vine-Programming Tech\"",
    "11": "Forest Sign \"Manufactured Vine-Programming Tech\"",
    "12": "Lake Sign \"Where Water and Land Meet\"",
    "13": "Nature Sign \"Youkai-Made Canal\"",
    "14": "Canal Sign \"Yamashiro and Kappa Conflict\"",
    "15": "Canal Sign \"Yamashiro and Kappa at War\"",
    "16": "Leaf Skill \"Truely Green Spiral\"",
    "18": "Leaf Skill \"Truely Green Cyclone\"",
    "19": "Leaf Skill \"Truely Green Tornado\"",
	
    "20": "Mountain Sign \"Ground-Breaking Kumomagusa\"",
    "22": "Mountain Apparition \"Heaven-Shaking Kumomagusa\"",
    "24": "Mountain Sign \"Usuyukisou Shining with Bewitching Light\"",
    "26": "Mountain Apparition \"Usuyukisou of Thronging Crowds of Youma\"",
    "28": "Mountain Flower \"Komakusa of Massacre\"",
    "30": "Mountain Flower \"Mountain Queen of Massacre\"",
	
	"109": "Jeweled Train \"The Ying-Yang Express\"",
	
    "32": "Preemptive Party Start \"Playful Rainbow Pond\"",
    "34": "Preemptive Party Start \"The Rainbow River Conspiracy\"",
    "35": "Preemptive Party Start \"The Rainbow River Conspiracy\"",
    "36": "Cryptid Sign \"The Infinite Lake Monster Peaking Above the Surface\"",
    "37": "Cryptid Sign \"The Infinite Lake Monster Unveils Itself\"",
    "38": "Cryptid Sign \"The Infinite Lake Monster Strikes from Below\"",
    "39": "Cryptid Sign \"The Infinite Lake Monster Tsunami\"",
    "40": "Divine Tool \"Moriya's Iron Ring\"",
    "101": "Native Myth \"Jade Scroll of Ancient Frogs\"",
    "103": "Native Myth \"Jade Scroll of Ancient Frogs\"",
    "105": "Native God \"Mishaguji-sama\"",
	
	"113": "Illumination Illusion \"Lunar Lotus Shining Only on the Water's Surface\"",
	
    "44": "Kuda-gitsune \"Vile Vial of Bamboo\"",
    "46": "Kuda-gitsune \"Vile Vial of Shining Bamboo\"",
    "48": "Fox Sign \"Fox Enclosure\"",
    "50": "Fox Sign \"Fox Enclosure\"",
    "52": "Manipulation \"Whispering to a Weak Soul ~Mob Mentality~\"",
    "53": "Manipulation \"Whispering to a Troubled Soul ~All Ears~\"",
    "54": "Manipulation \"Whispering to a Injured Soul ~Loss of Will~\"",
    "55": "Manipulation \"Whispering to a Traumatized Soul ~Betray Thyself~\"",
    "56": "Fox Atlas \"Dance of a Thousand Oceans and Mountains\"",
    "58": "Fox Atlas \"Wild Dance of a Thousand Oceans and Mountains\"",
	
    "60": "\"Market's Closing Hour Rush\"",
    "64": "\"Wheels of Fortune\"",
    "68": "\"Bullet Bartering\"",
    "70": "\"Boisterous Bullet Bartering\"",
    "71": "\"Barbarous Bullet Bartering\"",
    "72": "\"Heaven Ring Danmaku Asylum\"",
    "76": "\"We'll All Go Riding on a Rainbow\"",
    "78": "\"We'll All Go Riding on a Rainbow\"",
    "79": "\"We'll All Go Riding on a Rainbow\"",
    "80": "\"Relinquished Moonbow\"",
	
    "84": "Ouroboros \"Fading God Renewing\"",
    "85": "Rice Sign \"Blessed Rains of Harvest\"",
    "86": "Onbashira \"Grand Shinto Shimenawa\"",
	
    "87": "Kodoku \"Cannibalistic Insect\"",
    "88": "Kodoku \"Cave Swarmer\"",
    "89": "Kodoku \"Sky Pendra\"",
    "90": "Mining \"Ever-Accumulating Mine Dump\"",
    "91": "Mining \"Mine Blast\"",
    "92": "Mining \"Shield Method of the Youkai\"",
    "93": "Oomukade-ception \"How Would a Dragon Eat a Snake?\"",
    "94": "Oomukade \"Kodoku Regular Family Meal\"",
    "95": "\"But There's Not a Lot of 700-Foot Centipedes Around to Love\"",
    "96": "\"Mushihime-sama's Caving In\"",
	
    "840": "Fox Sign \"Fox Winder\"",
    "850": "Kuda-gitsune \"Cylinder Fox\"",
    "860": "Stellar Fox \"Dance of Heavenly Foxes and Dragon Stars\"",
	
    "320": "Orb Sign \"Dragon Yin-Yang Orbs\"",
    "330": "Orb Sign \"Dragon Yin-Yang Orbs\"",
    "340": "Yin-Yang Orb Sign \"Rainbow Treasure Within the Mine Shaft\"",
    "350": "Yin-Yang Orb Sign \"Rainbow Treasure Within the Mine Shaft\"",
    "360": "Jeweled General \"Queen of Yin-Yang Sphere\"",
    "380": "Queenly Gem \"Beyond the Rainbow Door\"",
    "400": "\"Yin-Yang Suffocation\"",
	
    "440": "Calamitous Star \"Dance of the Wildfire Started by a Star's Spark\"",
    "460": "Calamitous Star \"Wild Dance of the Wildfire Started by a Star's Spark\"",
    "480": "Stellar Wind \"Dance of Dazzling Iridescence\"",
    "500": "Stellar Wind \"Wild Dance of Dazzling Iridescence\"",
    "520": "Luminous Horse \"Dance of Sky-Racing Heavenly Steeds\"",
    "540": "Luminous Horse \"Wild Dance of Sky-Racing Heavenly Steeds\"",
    "560": "Rainbow Illumination \"Clear and Tranquil Wind and Moon\"",
	
	
	"600": "\"An Offering to the Ownerless\"",
    "640": "\"Danmaku Hoarder's Obsession\"",
    "680": "\"Bullet Market\"",
    "700": "\"High Density Bullet Market\"",
    "710": "\"Danmaku Free Market\"",
    "720": "\"Rainbow Ring of People\"",
    "760": "\"Bullet Dominion\"",
    "780": "\"Tyrannical Bullet Dominion\"",
    "790": "\"Inhumane Bullet Dominion\"",
    "800": "\"Asylum of Danmaku\""
}