{
    "0": "Butterfly Sign \"Minute Scales\"",
    "2": "Butterfly Sign \"Swallowtail's Scales\"",
    "4": "Butterfly Sign \"Fluttering Summer\"",
    "6": "Butterfly Sign \"Midsummer Wingbeats\"",
	
    "8": "Rain Sign \"Imprisoning Autumn Rain\"",
    "10": "Rain Sign \"Cursed Torrential Rain\"",
    "12": "Blade Sign \"Yamanba's Kitchen Knife Sharpening\"",
    "14": "Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\"",
    "16": "Blade Exhaustion Sign \"Mountain Murder\"",
    "18": "Blade Exhaustion Sign \"Bloody Mountain Murder\"",
	
    "20": "Spring Sign \"Surprise Spring\"",
    "22": "Dog Sign \"Stray Dog's Walk\"",
    "24": "Hound Sign \"Mountain Hound's Walk\"",
    "26": "Spinning Top \"Koma-Inu Spin\"",
    "29": "Spinning Top \"Curl Up and Die\"",
    "30": "Koma Sign \"Solitary A-Um Breathing\"",
	
    "34": "Magic Sign \"Instant Bodhi\"",
    "36": "Magic Sign \"Bodhi in an Instant\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "40": "Magic Sign \"Gigantic Pet Bullet Lifeform\"",
    "42": "Jizo \"Criminal Salvation\"",
    "44": "Jizo \"Hellfire Salvation\"",
	
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myōga Ginger \"Forget Your Name\"",
    "54": "Broadleaf Sign \"Tanabata Star Festival\"",
    "58": "Myōga Blessing \"Behind You\"",
    "62": "Dance Sign \"Behind Festival\"",
    "66": "Mad Dance \"Tengu-odoshi\"",
    "68": "Mad Dance \"Frenzied Tengu-Frightening\"",
	
    "70": "Back Sign \"Halo of the Secret God\"",
    "73": "Back Sign \"Halo of the Absolute Secret God\"",
    "74": "Hidden Summer \"Scorch By Hot Summer\"",
    "76": "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
    "78": "Hidden Fall \"Die of Famine\"",
    "80": "Hidden Fall \"Preta of Abnormal Blight\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Hidden Spring \"April Wizard\"",
    "88": "Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
	
    "90": "\"Hidden Breezy Cherry Blossom\"",
    "94": "\"Hidden Perfect Summer Ice\"",
    "98": "\"Hidden Crazy Fall Wind\"",
    "102": "\"Hidden Extreme Winter\"",
	
    "106": "April Showers  \"Typhoon Phenomena\"",
    "107": "May Flowers \"Gensokyo Flora\"",
    "108": "Soft Spring Breeze \"Pink Sakura\"",

    "109": "Doyou \"Eternal Earthen Energy\"",
    "110": "Metamorphosis \"Insect's Cyclic Life\"",
    "111": "Chrysalis of Darkness \"Eternity Tripion\"",
    "112": "Pseudo Back Door \"Harness Doyou\"",
    "113": "Crowned \"Laurel Wreath\"",
    "114": "Summer's Heat Stroke \"Waves of Ra\"",
    "115": "Shinto Sign \"Scripture of Heaven\"",
    "116": "Secret Seasons \"Ritu Ritual -Monsoon and Dry-\"",
    "117": "Insanity of a Mere Cargo Cult \"Perpetual Darkness\"",
    "118": "God of the Everlasting World \"A Star of Hope Sets in the Sunset Sky\""
}