{
    "0": "Blizzard \"Sheer Cold\"",
    "2": "Roundabout \"Mad Tail Fin\"",
    "4": "Whirlpool \"Impossible Tail Fin Spin\"",
    "6": "Raging Scale Waves \"Revolution Song\"",
    "8": "\"Siren's Rebellious Scale Wave\"",
    "10": "Strange Art \"Dullahan's Spine\"",
    "14": "Rokurokubi's Flight \"Endless Neck\"",
    "16": "Anomaly \"Rokurokubi's Infinite Neck\"",
    "18": "Hell's Heads \"Cerberus\"",
    "19": "Hell's Heads \"Hydra\"",
    "21": "Heracles' Hurdle \"Lernaean Hydra\"",
    "22": "\"Nukekubi's Curse\"",
    "26": "Fang Sign \"Shadow Wolf's Gaping Maw\"",
    "28": "Werewolf \"3-Sided Transformation\"",
    "30": "Werewolf \"Star-Shaped Transformation\"",
    "32": "Howling in the Night \"Bright Full Moon\"",
    "34": "Roaring in the Night \"Blinding Full Moon\"",
    "36": "Endangered Sign \"Messenger of the Kami Spirits\"",
    "38": "Extinct \"I Walk, With That Wolf, That is No More\"",
    "40": "Buddhist Heikyoku \"The Bell Inside Jetavana\"",
    "44": "Prized Possession \"Hoichi the Earless' Biwa\"",
    "46": "Vengeful Soul \"Taira no Masakado\"",
    "48": "\"Wicked Musical Score\"",
    "49": "\"Wicked Double Score\"",
    "51": "\"Fantaisie Espagnole as Heard on a Biwa\"",
    "52": "Impermanence \"Anicca's Koto\"",
    "56": "Echo Chamber \"Heian's Reverberation\"",
    "58": "\"Heian's Peaceful Echo\"",
    "60": "Koto Requiem \"Social Upheaval\"",
    "63": "\"Hungarian Rhapsody No. 2 as Heard on a Koto\"",
    "64": "Uncertian Trail \"Finding Ambition\"",
    "68": "Backward Logic \"Duality of Right and Wrong\"",
    "70": "Amanojaku's Logic \"Duality of Love and Hate\"",
    "72": "Misjudgment \"Displacement Folley\"",
    "74": "Growing Unrest \"Disaray Under Heaven\"",
    "76": "\"Just Go Flip a Table Already, Will Ya?\"",
    "78": "\"To Flip a Mocking Bird\"",
    "80": "Absolute Tunabout \"The World Revolving\"",
    "83": "\"Seija's Inverted World\"",
    "84": "Sukunabikona \"It's a Small World\"",
    "86": "Inchling's Hell \"It's a Small World After All\"",
    "88": "Miracle Mallet \"Grow Even Bigger!\"",
    "90": "Miracle Mallet \"Grow Your Biggest!\"",
    "92": "Warrior's Legend \"Shining Needle Sword of the Inchlings\"",
    "96": "Mallet's Curse \"You Grow Bigger!\"",
    "100": "Attack on Dwarf \"Wall of Issun\"",
    "102": "\"Issun's Fortress\"",
    "104": "\"The Descendants of the Legendary Oni Slayer\"",
    "107": "\"Shinmyoumaru's Destiny\"",
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Drum \"Raging Temple Taiko\"",
    "111": "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Drum \"Three Strikes at Midnight\"",
    "113": "Death Drum \"Land Percuss\"",
    "114": "Fifth Drum \"Den-Den Daiko\"",
    "115": "Sixth Drum \"Alternate Sticking\"",
    "116": "Seventh Drum \"High Speed Taiko Rocket\"",
    "117": "Eighth Drum \"Thunder God's Anger\"",
    "118": "\"Blue Lady Show\"",
    "119": "\"Pristine Beat\""
}
}