{
    "901": "\"LoLK EX\"",
    "0": "\"Reimu nonspell\"",
    "1": "\"Reimu nonspell\"",
	
    "902": "\"WBaWC 2\"",
    "2": "River Sign \"Paths of the Sanzu\"",
    "3": "Ordeal \"Sunrise Land from the Palm\"",
    "4": "Drowning Sign \"Nure-onna's Plea\"",
    "5": "\"Ordeal of Falling Feathers ~Follow Along with Me!~\"",
	
    "903": "\"HSiFS 1 Edited\"",
    "6": "\"Nemuno Nonspell\"",
    "7": "Chrysalis \"Nature's Miracle ~Sunflower Pupa~\"",
    "8BETA": "Cave Sign \"Out of Season Yeti Den\"",
	 "8": "Rain Blade \"Yorimitsu's Golden Downpour\"",
	
    "904": "\"WBaWC 1\" Awaiting Sacred Life",
    "9": "Light Sign \"A Star Over Horizon\"",
    "10": "\"Spirit of the Turritopsis Dohrnii\"",
    "11": "Frosty Seal \"A Jizo Turned Back into Stone\"",
    "12": "Limbo \"Stone Stacking in Memoriam\"",
	
    "905": "\"LoLK 2\"",
    "13": "Guardian Sign \"Komainu and the Mysterious Spring Lane\"",
    "14": "Gun Sign \"The Soaring Eagle Across Dimensions\"",
    "15": "Apple \"Brightening Red Dango\"",
	
    "906": "\"DDC 3\"",
    "16": "\"Youmu nonspell\"",
    "17": "Confusing Conjuring \"Misplaced in Time\"",
    "18": "Esoterica \"Secret Sparkling Star ~Miracle Boundary~\"",
	
    "906": "\"LoLK 3\"",
	"19": "\"Unravelling Thoughts in Celadon\"",

    "906": "\"LoLK 3 Climax\"",
    "20": "Dream Barrier \"Worn Out Fantasy\"",	
    "21": "Dream Beast \"Beast Fishing Xing\"",
    "22": "Dream Ordeal \"Judgement Wings ~Lethal Oniwatari~\"",
    "23": "Dream Season \"Etarnity's Summer Harvest ~Doyou~\"",
    "24": "Dream in Limbo \"Let Me Be Heaven Bound\"",
    "25": "Dream Dango \"Ringo Brand Dango ~Moon Flavored~\"",
    "26": "Dream God Sword \"Tommorow Slicing Rifts into the Past\"",

    "906": "\"UFO 4\"",
    "28": "\"Jo'on nonspell\"",
    "28": "Economic Crash \"Great Recession\"",
    "29": "Con-Artistry \"Yorigami Gold Rush\"",
    "30": "Psuedo-Possession \"Tonight's Biggest Loser\"",
	
    "906": "\"TD 4\"",
    "31": "\"Kokoro nonspell\"",
    "32": "Mask Sign \"Vibe Ballad\"",
    "33": "Orb Sign \"Purity Filtering Duplex Stairway\"",
    "34": "Theatre in the Round \"Noh of Darkness\"",
	
    "906": "\"LoLK 4\"",
	"35": "Lucidiy \"Sydney Street Light Epiphany\"",
    "36": "Hell Sign \"Caged in Spangled Stars and Broad Stripes\"",
    "37": " Ōmagatoki \"Welcome, a Lovely Trip to Hell ~Agony Inferno~\"",
    "38": "\"Tragic Ocean\"",
    "39": "\"Junko & Hecatia\"",
    "40": "Mesmerism \"Lost in Luna's Eyes ~Hazy, Dazing Gaze~\"",

    "906": "\"WBaWC 5\"",
    "41": "\"Keiki nonspell\"",
    "42": "Sculpting Art \"The Creation of Tiryagyoni\"",
    "43": "Haywire Sign \"Do Haniwa Dream of Ceramic Sheep?\"",
    "44": "\"Hero and Her Impenetrable, Creature-Destroying Masterpeice\"",
    "45": "Q.E.D. \"Geometrize World\"",
	
    "906": "\"WBaWC EX\"",
    "46": "\"Yachie\"",
    "47": "Jidao \"The Beast Outside an Ever-Fragmenting Window\"",
    "48": "Dragon Sign \"Soul-Crushing Tortoiseshell Fortress\"",
    "49": "Agile Skill \"Titan Kick\"",
    "50": "\"Wily Beast Cyclone\"",

    "906": "\"HSiFS 6\"",
    "51": "\"Bamboo to Afterlife ~How Low Can I Go?~\"",
    "52": "Genshou Phenomenon \"You Forget Me, as I Do to You\"",
    "53": "Camaraderie \"Beloving Pirouette into Backdoor\"",
    "54": "\"Okina nonspell\"",
    "55": "Secret Ceremony \"Gates to an Infinite Labyrinth\"",
    "56": "Back Door \"Matarah Vijnana\"",
	
    "906": "\"PCB 6\"",
    "57": "Ghastly Dance \"Saigyouji Afterlife Ritual ~Mahasamadhi~\"",
    "58": "Judgement \"Ascension into a Monochrome World\"",
    "59": "Khanti \"Forbidden Sorcery Extravaganza\"",
    "60": "Hermit Sign \"Fabulously, Absolutely Starry Shaku Light\"",
    "61": "Possession \"Souls of a Boisterious, Backstabbing Ballroom\"",
    "62": "Sealing Art \"Ultimate Spring Elegance\"",
	
    "906": "\"MoF 6 (Pre-transition) or 4\"",
    "63": "Virtue \"Wind God's Stairway ~Ascension~\"",
    "64": "\"Gravitational Supernova\"",
    "65": "Wish \"Voyage to the Dotonbori River Canal\"",
    "66": "Woofer \"Summer Thunder Surfin'\"",
    "67": "Mallet \"Grow Bigger, My Taiko!\"",
    "68": "\"Wind God Lake's Autumnal Fafrotskies\"",
	
    "906": "\"IN 6a\"",
    "69": "Unknown Comet \"Space Falcon Flying the Cosmos\"",
    "70": "Impossible Request Neo \"Tavern in Blue ~Hopeless Purity~\"",
    "71": "Vampire Art \"Silver Stake to the Grave\"",
    "72": "Awakening \"Phoenix by Summoning ~Ringing of Suzu~\"",
    "73": "Altered Treasure \"Galaxy in Buddha's Bowl\"",
    "74": "\"Phantom Blood\"",
	
    "906": "\"UFO EX\"",
	"75": "Forbidden Barrage \"Carousel of Agony\"",
    "75ALT": "Forbidden Barrage \"Ternion Cage ~Ring Around the Rosie~\"",
    "76": "Native Myth \"Vanishing Amphibian Sun Maiden\"",
    "77": "\"Unknown Nebula\"",
    "78": "Shikigami \"Instant God Messenger\"",
    "79": "Seventy-Ninth Duel \"Flag on the False Moon ~Modern Lure~\"",
    "80ALPHA": "(KOISHI) Symbolism \"Sacred Kiss of Heartbreak\"",
	"80BETA": "\"Advanced Plaque Entaglements\"",
	"80": "\"Complete Subconscious Control\"",
	
    "906": "\"LoLK 6\"",
    "81": "\"Earthly Wonder, Heavenly Power, Peachy Peace\"",
    "82": "Agile Skill \"Speed Demon\"",
    "83": "Moon \"Apollo's Broken Chains\"",
    "84": "\"Pandemonium in Stupor\"",
    "85": "Jagged Lemniscate Shape \"Creature Uchigi Trap\"",
    "86": "\"Impurity Ark\"",
	
    "906": "\"CUSTOM?\"",
    "87": "\"Ichirn & Wakasagihime nonspell\"",
    "88": "\"Exposing the Mysterious New Reporter in Town\"",
    "89": "\"Kappa Alpha Program ~Evangelion~\"",
    "90": "Reverse Spell \"10 Tales from a Not-So Wonderful Land\"",
    "91": "Ceremony Link \"Defiled Star Season\"",
    "92": "Dream \"Beloved Ice Columns Lost in a Nightmarish State\"",

    "906": "\"GFW EX\"",
	
    "93": "Secret Ceremony \"Gohonzon Backdoor\"",
    "94": "Exorcism \"Sealing Square for the Unauthorized ~Capture~\"",
    "95": "Evil Spirits \"Ecosystem of Esotric and Public\"",
    "96": "\"Industriously Rogue Ordinary Magician\"",
    "97": "\"Absolute Border Bullet Hell\"",
    "98": "\"Recollections of Red, White, & Black\"",
	
    "906": "\"LoLK EX Edited\"",
    "99": "\"Terminal Lucidty Phenomena\"",
    "100": "Origami Sign \"Zener Card Shuriken EX\"",
    "101": "\"Vanishing into Otherworldly Reverie ~Idol & Rebellion~\"",
	
    "187": "\"Monkey Possession\"",
    "188": "Egotistical Paparazzi Reporters \"Esoteric Eagerly Exposed!\"",
    "189": "\"The Most Despicable and Disastrous Elder God\"",
    "190": "Team Tech Speedrun \"Prankster Comet -Impatient Fairies-\"",
    "191": "\"Pandemonium of a Gathering Reverie\"",
    "192": "\"Scarlet Weather Rapture\""
}